/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package network;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TPlayer implements TEnum {
  NONE(0),
  RED_ONE(1),
  RED_TWO(2),
  BLUE_ONE(3),
  BLUE_TWO(4);

  private final int value;

  private TPlayer(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TPlayer findByValue(int value) { 
    switch (value) {
      case 0:
        return NONE;
      case 1:
        return RED_ONE;
      case 2:
        return RED_TWO;
      case 3:
        return BLUE_ONE;
      case 4:
        return BLUE_TWO;
      default:
        return null;
    }
  }
}
