/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package network;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

public class TPaddle implements TBase<TPaddle, TPaddle._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("TPaddle");

  private static final TField RADIUS_FIELD_DESC = new TField("radius", TType.DOUBLE, (short)1);
  private static final TField ANGLE_FIELD_DESC = new TField("angle", TType.DOUBLE, (short)2);
  private static final TField LENGTH_FIELD_DESC = new TField("length", TType.DOUBLE, (short)3);
  private static final TField PLAYER_FIELD_DESC = new TField("player", TType.I32, (short)4);
  private static final TField IS_INVISIBLE_FIELD_DESC = new TField("isInvisible", TType.BOOL, (short)5);
  private static final TField IS_SPEEDUP_FIELD_DESC = new TField("isSpeedup", TType.BOOL, (short)6);
  private static final TField IS_MAGNETIC_FIELD_DESC = new TField("isMagnetic", TType.BOOL, (short)7);

  public double radius;
  public double angle;
  public double length;
  /**
   * 
   * @see TPlayer
   */
  public TPlayer player;
  public boolean isInvisible;
  public boolean isSpeedup;
  public boolean isMagnetic;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    RADIUS((short)1, "radius"),
    ANGLE((short)2, "angle"),
    LENGTH((short)3, "length"),
    /**
     * 
     * @see TPlayer
     */
    PLAYER((short)4, "player"),
    IS_INVISIBLE((short)5, "isInvisible"),
    IS_SPEEDUP((short)6, "isSpeedup"),
    IS_MAGNETIC((short)7, "isMagnetic");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RADIUS
          return RADIUS;
        case 2: // ANGLE
          return ANGLE;
        case 3: // LENGTH
          return LENGTH;
        case 4: // PLAYER
          return PLAYER;
        case 5: // IS_INVISIBLE
          return IS_INVISIBLE;
        case 6: // IS_SPEEDUP
          return IS_SPEEDUP;
        case 7: // IS_MAGNETIC
          return IS_MAGNETIC;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RADIUS_ISSET_ID = 0;
  private static final int __ANGLE_ISSET_ID = 1;
  private static final int __LENGTH_ISSET_ID = 2;
  private static final int __ISINVISIBLE_ISSET_ID = 3;
  private static final int __ISSPEEDUP_ISSET_ID = 4;
  private static final int __ISMAGNETIC_ISSET_ID = 5;
  private BitSet __isset_bit_vector = new BitSet(6);

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RADIUS, new FieldMetaData("radius", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.DOUBLE)));
    tmpMap.put(_Fields.ANGLE, new FieldMetaData("angle", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.DOUBLE)));
    tmpMap.put(_Fields.LENGTH, new FieldMetaData("length", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.DOUBLE)));
    tmpMap.put(_Fields.PLAYER, new FieldMetaData("player", TFieldRequirementType.DEFAULT, 
        new EnumMetaData(TType.ENUM, TPlayer.class)));
    tmpMap.put(_Fields.IS_INVISIBLE, new FieldMetaData("isInvisible", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.BOOL)));
    tmpMap.put(_Fields.IS_SPEEDUP, new FieldMetaData("isSpeedup", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.BOOL)));
    tmpMap.put(_Fields.IS_MAGNETIC, new FieldMetaData("isMagnetic", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.BOOL)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(TPaddle.class, metaDataMap);
  }

  public TPaddle() {
  }

  public TPaddle(
    double radius,
    double angle,
    double length,
    TPlayer player,
    boolean isInvisible,
    boolean isSpeedup,
    boolean isMagnetic)
  {
    this();
    this.radius = radius;
    setRadiusIsSet(true);
    this.angle = angle;
    setAngleIsSet(true);
    this.length = length;
    setLengthIsSet(true);
    this.player = player;
    this.isInvisible = isInvisible;
    setIsInvisibleIsSet(true);
    this.isSpeedup = isSpeedup;
    setIsSpeedupIsSet(true);
    this.isMagnetic = isMagnetic;
    setIsMagneticIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TPaddle(TPaddle other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.radius = other.radius;
    this.angle = other.angle;
    this.length = other.length;
    if (other.isSetPlayer()) {
      this.player = other.player;
    }
    this.isInvisible = other.isInvisible;
    this.isSpeedup = other.isSpeedup;
    this.isMagnetic = other.isMagnetic;
  }

  public TPaddle deepCopy() {
    return new TPaddle(this);
  }

  @Override
  public void clear() {
    setRadiusIsSet(false);
    this.radius = 0.0;
    setAngleIsSet(false);
    this.angle = 0.0;
    setLengthIsSet(false);
    this.length = 0.0;
    this.player = null;
    setIsInvisibleIsSet(false);
    this.isInvisible = false;
    setIsSpeedupIsSet(false);
    this.isSpeedup = false;
    setIsMagneticIsSet(false);
    this.isMagnetic = false;
  }

  public double getRadius() {
    return this.radius;
  }

  public TPaddle setRadius(double radius) {
    this.radius = radius;
    setRadiusIsSet(true);
    return this;
  }

  public void unsetRadius() {
    __isset_bit_vector.clear(__RADIUS_ISSET_ID);
  }

  /** Returns true if field radius is set (has been asigned a value) and false otherwise */
  public boolean isSetRadius() {
    return __isset_bit_vector.get(__RADIUS_ISSET_ID);
  }

  public void setRadiusIsSet(boolean value) {
    __isset_bit_vector.set(__RADIUS_ISSET_ID, value);
  }

  public double getAngle() {
    return this.angle;
  }

  public TPaddle setAngle(double angle) {
    this.angle = angle;
    setAngleIsSet(true);
    return this;
  }

  public void unsetAngle() {
    __isset_bit_vector.clear(__ANGLE_ISSET_ID);
  }

  /** Returns true if field angle is set (has been asigned a value) and false otherwise */
  public boolean isSetAngle() {
    return __isset_bit_vector.get(__ANGLE_ISSET_ID);
  }

  public void setAngleIsSet(boolean value) {
    __isset_bit_vector.set(__ANGLE_ISSET_ID, value);
  }

  public double getLength() {
    return this.length;
  }

  public TPaddle setLength(double length) {
    this.length = length;
    setLengthIsSet(true);
    return this;
  }

  public void unsetLength() {
    __isset_bit_vector.clear(__LENGTH_ISSET_ID);
  }

  /** Returns true if field length is set (has been asigned a value) and false otherwise */
  public boolean isSetLength() {
    return __isset_bit_vector.get(__LENGTH_ISSET_ID);
  }

  public void setLengthIsSet(boolean value) {
    __isset_bit_vector.set(__LENGTH_ISSET_ID, value);
  }

  /**
   * 
   * @see TPlayer
   */
  public TPlayer getPlayer() {
    return this.player;
  }

  /**
   * 
   * @see TPlayer
   */
  public TPaddle setPlayer(TPlayer player) {
    this.player = player;
    return this;
  }

  public void unsetPlayer() {
    this.player = null;
  }

  /** Returns true if field player is set (has been asigned a value) and false otherwise */
  public boolean isSetPlayer() {
    return this.player != null;
  }

  public void setPlayerIsSet(boolean value) {
    if (!value) {
      this.player = null;
    }
  }

  public boolean isIsInvisible() {
    return this.isInvisible;
  }

  public TPaddle setIsInvisible(boolean isInvisible) {
    this.isInvisible = isInvisible;
    setIsInvisibleIsSet(true);
    return this;
  }

  public void unsetIsInvisible() {
    __isset_bit_vector.clear(__ISINVISIBLE_ISSET_ID);
  }

  /** Returns true if field isInvisible is set (has been asigned a value) and false otherwise */
  public boolean isSetIsInvisible() {
    return __isset_bit_vector.get(__ISINVISIBLE_ISSET_ID);
  }

  public void setIsInvisibleIsSet(boolean value) {
    __isset_bit_vector.set(__ISINVISIBLE_ISSET_ID, value);
  }

  public boolean isIsSpeedup() {
    return this.isSpeedup;
  }

  public TPaddle setIsSpeedup(boolean isSpeedup) {
    this.isSpeedup = isSpeedup;
    setIsSpeedupIsSet(true);
    return this;
  }

  public void unsetIsSpeedup() {
    __isset_bit_vector.clear(__ISSPEEDUP_ISSET_ID);
  }

  /** Returns true if field isSpeedup is set (has been asigned a value) and false otherwise */
  public boolean isSetIsSpeedup() {
    return __isset_bit_vector.get(__ISSPEEDUP_ISSET_ID);
  }

  public void setIsSpeedupIsSet(boolean value) {
    __isset_bit_vector.set(__ISSPEEDUP_ISSET_ID, value);
  }

  public boolean isIsMagnetic() {
    return this.isMagnetic;
  }

  public TPaddle setIsMagnetic(boolean isMagnetic) {
    this.isMagnetic = isMagnetic;
    setIsMagneticIsSet(true);
    return this;
  }

  public void unsetIsMagnetic() {
    __isset_bit_vector.clear(__ISMAGNETIC_ISSET_ID);
  }

  /** Returns true if field isMagnetic is set (has been asigned a value) and false otherwise */
  public boolean isSetIsMagnetic() {
    return __isset_bit_vector.get(__ISMAGNETIC_ISSET_ID);
  }

  public void setIsMagneticIsSet(boolean value) {
    __isset_bit_vector.set(__ISMAGNETIC_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RADIUS:
      if (value == null) {
        unsetRadius();
      } else {
        setRadius((Double)value);
      }
      break;

    case ANGLE:
      if (value == null) {
        unsetAngle();
      } else {
        setAngle((Double)value);
      }
      break;

    case LENGTH:
      if (value == null) {
        unsetLength();
      } else {
        setLength((Double)value);
      }
      break;

    case PLAYER:
      if (value == null) {
        unsetPlayer();
      } else {
        setPlayer((TPlayer)value);
      }
      break;

    case IS_INVISIBLE:
      if (value == null) {
        unsetIsInvisible();
      } else {
        setIsInvisible((Boolean)value);
      }
      break;

    case IS_SPEEDUP:
      if (value == null) {
        unsetIsSpeedup();
      } else {
        setIsSpeedup((Boolean)value);
      }
      break;

    case IS_MAGNETIC:
      if (value == null) {
        unsetIsMagnetic();
      } else {
        setIsMagnetic((Boolean)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RADIUS:
      return new Double(getRadius());

    case ANGLE:
      return new Double(getAngle());

    case LENGTH:
      return new Double(getLength());

    case PLAYER:
      return getPlayer();

    case IS_INVISIBLE:
      return new Boolean(isIsInvisible());

    case IS_SPEEDUP:
      return new Boolean(isIsSpeedup());

    case IS_MAGNETIC:
      return new Boolean(isIsMagnetic());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RADIUS:
      return isSetRadius();
    case ANGLE:
      return isSetAngle();
    case LENGTH:
      return isSetLength();
    case PLAYER:
      return isSetPlayer();
    case IS_INVISIBLE:
      return isSetIsInvisible();
    case IS_SPEEDUP:
      return isSetIsSpeedup();
    case IS_MAGNETIC:
      return isSetIsMagnetic();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TPaddle)
      return this.equals((TPaddle)that);
    return false;
  }

  public boolean equals(TPaddle that) {
    if (that == null)
      return false;

    boolean this_present_radius = true;
    boolean that_present_radius = true;
    if (this_present_radius || that_present_radius) {
      if (!(this_present_radius && that_present_radius))
        return false;
      if (this.radius != that.radius)
        return false;
    }

    boolean this_present_angle = true;
    boolean that_present_angle = true;
    if (this_present_angle || that_present_angle) {
      if (!(this_present_angle && that_present_angle))
        return false;
      if (this.angle != that.angle)
        return false;
    }

    boolean this_present_length = true;
    boolean that_present_length = true;
    if (this_present_length || that_present_length) {
      if (!(this_present_length && that_present_length))
        return false;
      if (this.length != that.length)
        return false;
    }

    boolean this_present_player = true && this.isSetPlayer();
    boolean that_present_player = true && that.isSetPlayer();
    if (this_present_player || that_present_player) {
      if (!(this_present_player && that_present_player))
        return false;
      if (!this.player.equals(that.player))
        return false;
    }

    boolean this_present_isInvisible = true;
    boolean that_present_isInvisible = true;
    if (this_present_isInvisible || that_present_isInvisible) {
      if (!(this_present_isInvisible && that_present_isInvisible))
        return false;
      if (this.isInvisible != that.isInvisible)
        return false;
    }

    boolean this_present_isSpeedup = true;
    boolean that_present_isSpeedup = true;
    if (this_present_isSpeedup || that_present_isSpeedup) {
      if (!(this_present_isSpeedup && that_present_isSpeedup))
        return false;
      if (this.isSpeedup != that.isSpeedup)
        return false;
    }

    boolean this_present_isMagnetic = true;
    boolean that_present_isMagnetic = true;
    if (this_present_isMagnetic || that_present_isMagnetic) {
      if (!(this_present_isMagnetic && that_present_isMagnetic))
        return false;
      if (this.isMagnetic != that.isMagnetic)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TPaddle other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TPaddle typedOther = (TPaddle)other;

    lastComparison = Boolean.valueOf(isSetRadius()).compareTo(typedOther.isSetRadius());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRadius()) {
      lastComparison = TBaseHelper.compareTo(this.radius, typedOther.radius);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAngle()).compareTo(typedOther.isSetAngle());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAngle()) {
      lastComparison = TBaseHelper.compareTo(this.angle, typedOther.angle);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLength()).compareTo(typedOther.isSetLength());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLength()) {
      lastComparison = TBaseHelper.compareTo(this.length, typedOther.length);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPlayer()).compareTo(typedOther.isSetPlayer());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayer()) {
      lastComparison = TBaseHelper.compareTo(this.player, typedOther.player);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsInvisible()).compareTo(typedOther.isSetIsInvisible());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsInvisible()) {
      lastComparison = TBaseHelper.compareTo(this.isInvisible, typedOther.isInvisible);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsSpeedup()).compareTo(typedOther.isSetIsSpeedup());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsSpeedup()) {
      lastComparison = TBaseHelper.compareTo(this.isSpeedup, typedOther.isSpeedup);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIsMagnetic()).compareTo(typedOther.isSetIsMagnetic());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsMagnetic()) {
      lastComparison = TBaseHelper.compareTo(this.isMagnetic, typedOther.isMagnetic);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // RADIUS
          if (field.type == TType.DOUBLE) {
            this.radius = iprot.readDouble();
            setRadiusIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // ANGLE
          if (field.type == TType.DOUBLE) {
            this.angle = iprot.readDouble();
            setAngleIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // LENGTH
          if (field.type == TType.DOUBLE) {
            this.length = iprot.readDouble();
            setLengthIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // PLAYER
          if (field.type == TType.I32) {
            this.player = TPlayer.findByValue(iprot.readI32());
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // IS_INVISIBLE
          if (field.type == TType.BOOL) {
            this.isInvisible = iprot.readBool();
            setIsInvisibleIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 6: // IS_SPEEDUP
          if (field.type == TType.BOOL) {
            this.isSpeedup = iprot.readBool();
            setIsSpeedupIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 7: // IS_MAGNETIC
          if (field.type == TType.BOOL) {
            this.isMagnetic = iprot.readBool();
            setIsMagneticIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    oprot.writeFieldBegin(RADIUS_FIELD_DESC);
    oprot.writeDouble(this.radius);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(ANGLE_FIELD_DESC);
    oprot.writeDouble(this.angle);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(LENGTH_FIELD_DESC);
    oprot.writeDouble(this.length);
    oprot.writeFieldEnd();
    if (this.player != null) {
      oprot.writeFieldBegin(PLAYER_FIELD_DESC);
      oprot.writeI32(this.player.getValue());
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(IS_INVISIBLE_FIELD_DESC);
    oprot.writeBool(this.isInvisible);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(IS_SPEEDUP_FIELD_DESC);
    oprot.writeBool(this.isSpeedup);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(IS_MAGNETIC_FIELD_DESC);
    oprot.writeBool(this.isMagnetic);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TPaddle(");
    boolean first = true;

    sb.append("radius:");
    sb.append(this.radius);
    first = false;
    if (!first) sb.append(", ");
    sb.append("angle:");
    sb.append(this.angle);
    first = false;
    if (!first) sb.append(", ");
    sb.append("length:");
    sb.append(this.length);
    first = false;
    if (!first) sb.append(", ");
    sb.append("player:");
    if (this.player == null) {
      sb.append("null");
    } else {
      sb.append(this.player);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("isInvisible:");
    sb.append(this.isInvisible);
    first = false;
    if (!first) sb.append(", ");
    sb.append("isSpeedup:");
    sb.append(this.isSpeedup);
    first = false;
    if (!first) sb.append(", ");
    sb.append("isMagnetic:");
    sb.append(this.isMagnetic);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }

}

