/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package network;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

public class TPosition implements TBase<TPosition, TPosition._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("TPosition");

  private static final TField X_POS_FIELD_DESC = new TField("xPos", TType.DOUBLE, (short)1);
  private static final TField Y_POS_FIELD_DESC = new TField("yPos", TType.DOUBLE, (short)2);

  public double xPos;
  public double yPos;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    X_POS((short)1, "xPos"),
    Y_POS((short)2, "yPos");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // X_POS
          return X_POS;
        case 2: // Y_POS
          return Y_POS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __XPOS_ISSET_ID = 0;
  private static final int __YPOS_ISSET_ID = 1;
  private BitSet __isset_bit_vector = new BitSet(2);

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.X_POS, new FieldMetaData("xPos", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.DOUBLE)));
    tmpMap.put(_Fields.Y_POS, new FieldMetaData("yPos", TFieldRequirementType.DEFAULT, 
        new FieldValueMetaData(TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(TPosition.class, metaDataMap);
  }

  public TPosition() {
  }

  public TPosition(
    double xPos,
    double yPos)
  {
    this();
    this.xPos = xPos;
    setXPosIsSet(true);
    this.yPos = yPos;
    setYPosIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TPosition(TPosition other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    this.xPos = other.xPos;
    this.yPos = other.yPos;
  }

  public TPosition deepCopy() {
    return new TPosition(this);
  }

  @Override
  public void clear() {
    setXPosIsSet(false);
    this.xPos = 0.0;
    setYPosIsSet(false);
    this.yPos = 0.0;
  }

  public double getXPos() {
    return this.xPos;
  }

  public TPosition setXPos(double xPos) {
    this.xPos = xPos;
    setXPosIsSet(true);
    return this;
  }

  public void unsetXPos() {
    __isset_bit_vector.clear(__XPOS_ISSET_ID);
  }

  /** Returns true if field xPos is set (has been asigned a value) and false otherwise */
  public boolean isSetXPos() {
    return __isset_bit_vector.get(__XPOS_ISSET_ID);
  }

  public void setXPosIsSet(boolean value) {
    __isset_bit_vector.set(__XPOS_ISSET_ID, value);
  }

  public double getYPos() {
    return this.yPos;
  }

  public TPosition setYPos(double yPos) {
    this.yPos = yPos;
    setYPosIsSet(true);
    return this;
  }

  public void unsetYPos() {
    __isset_bit_vector.clear(__YPOS_ISSET_ID);
  }

  /** Returns true if field yPos is set (has been asigned a value) and false otherwise */
  public boolean isSetYPos() {
    return __isset_bit_vector.get(__YPOS_ISSET_ID);
  }

  public void setYPosIsSet(boolean value) {
    __isset_bit_vector.set(__YPOS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case X_POS:
      if (value == null) {
        unsetXPos();
      } else {
        setXPos((Double)value);
      }
      break;

    case Y_POS:
      if (value == null) {
        unsetYPos();
      } else {
        setYPos((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case X_POS:
      return new Double(getXPos());

    case Y_POS:
      return new Double(getYPos());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case X_POS:
      return isSetXPos();
    case Y_POS:
      return isSetYPos();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TPosition)
      return this.equals((TPosition)that);
    return false;
  }

  public boolean equals(TPosition that) {
    if (that == null)
      return false;

    boolean this_present_xPos = true;
    boolean that_present_xPos = true;
    if (this_present_xPos || that_present_xPos) {
      if (!(this_present_xPos && that_present_xPos))
        return false;
      if (this.xPos != that.xPos)
        return false;
    }

    boolean this_present_yPos = true;
    boolean that_present_yPos = true;
    if (this_present_yPos || that_present_yPos) {
      if (!(this_present_yPos && that_present_yPos))
        return false;
      if (this.yPos != that.yPos)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TPosition other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TPosition typedOther = (TPosition)other;

    lastComparison = Boolean.valueOf(isSetXPos()).compareTo(typedOther.isSetXPos());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetXPos()) {
      lastComparison = TBaseHelper.compareTo(this.xPos, typedOther.xPos);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetYPos()).compareTo(typedOther.isSetYPos());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetYPos()) {
      lastComparison = TBaseHelper.compareTo(this.yPos, typedOther.yPos);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // X_POS
          if (field.type == TType.DOUBLE) {
            this.xPos = iprot.readDouble();
            setXPosIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // Y_POS
          if (field.type == TType.DOUBLE) {
            this.yPos = iprot.readDouble();
            setYPosIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    oprot.writeFieldBegin(X_POS_FIELD_DESC);
    oprot.writeDouble(this.xPos);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(Y_POS_FIELD_DESC);
    oprot.writeDouble(this.yPos);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TPosition(");
    boolean first = true;

    sb.append("xPos:");
    sb.append(this.xPos);
    first = false;
    if (!first) sb.append(", ");
    sb.append("yPos:");
    sb.append(this.yPos);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }

}

